/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.core.HolderLookup$Provider
 *  net.minecraft.core.registries.BuiltInRegistries
 *  net.minecraft.data.PackOutput
 *  net.minecraft.data.recipes.RecipeCategory
 *  net.minecraft.data.recipes.RecipeOutput
 *  net.minecraft.data.recipes.RecipeProvider
 *  net.minecraft.data.recipes.ShapedRecipeBuilder
 *  net.minecraft.data.recipes.ShapelessRecipeBuilder
 *  net.minecraft.data.recipes.SimpleCookingRecipeBuilder
 *  net.minecraft.nbt.CompoundTag
 *  net.minecraft.nbt.Tag
 *  net.minecraft.tags.ItemTags
 *  net.minecraft.tags.TagKey
 *  net.minecraft.world.entity.EntityType
 *  net.minecraft.world.item.ItemStack
 *  net.minecraft.world.item.Items
 *  net.minecraft.world.item.crafting.Ingredient
 *  net.minecraft.world.level.ItemLike
 *  net.minecraft.world.level.block.Blocks
 *  net.neoforged.neoforge.common.Tags$Items
 */
package elucent.rootsclassic.datagen.server;

import elucent.rootsclassic.Const;
import elucent.rootsclassic.component.ComponentRegistry;
import elucent.rootsclassic.datagen.recipe.ComponentRecipeBuilder;
import elucent.rootsclassic.datagen.recipe.RitualRecipeBuilder;
import elucent.rootsclassic.registry.RootsRegistry;
import elucent.rootsclassic.ritual.RitualRegistry;
import java.util.concurrent.CompletableFuture;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.data.PackOutput;
import net.minecraft.data.recipes.RecipeCategory;
import net.minecraft.data.recipes.RecipeOutput;
import net.minecraft.data.recipes.RecipeProvider;
import net.minecraft.data.recipes.ShapedRecipeBuilder;
import net.minecraft.data.recipes.ShapelessRecipeBuilder;
import net.minecraft.data.recipes.SimpleCookingRecipeBuilder;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.Tag;
import net.minecraft.tags.ItemTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.neoforge.common.Tags;

public class RootsRecipeProvider
extends RecipeProvider {
    public RootsRecipeProvider(PackOutput packOutput, CompletableFuture<HolderLookup.Provider> lookupProvider) {
        super(packOutput, lookupProvider);
    }

    protected void buildRecipes(RecipeOutput consumer, HolderLookup.Provider holderLookup) {
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)RootsRegistry.PESTLE.get())).define(Character.valueOf('X'), (ItemLike)Blocks.DIORITE).group("pestle").pattern("X  ").pattern(" XX").pattern(" XX").unlockedBy("has_diorite", RootsRecipeProvider.has((ItemLike)Blocks.DIORITE)).save(consumer);
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)RootsRegistry.PESTLE.get())).define(Character.valueOf('X'), (ItemLike)Blocks.DIORITE).group("pestle").pattern("  X").pattern("XX ").pattern("XX ").unlockedBy("has_diorite", RootsRecipeProvider.has((ItemLike)Blocks.DIORITE)).save(consumer, String.valueOf(RootsRegistry.PESTLE.getId()) + "2");
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)RootsRegistry.MORTAR.get())).define(Character.valueOf('X'), Tags.Items.STONES).pattern("X X").pattern("X X").pattern(" X ").unlockedBy("has_stone", RootsRecipeProvider.has((TagKey)Tags.Items.STONES)).save(consumer);
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)RootsRegistry.IMBUER.get())).define(Character.valueOf('X'), Tags.Items.RODS_WOODEN).define(Character.valueOf('L'), ItemTags.LOGS).define(Character.valueOf('S'), (ItemLike)Blocks.CHISELED_STONE_BRICKS).pattern("X X").pattern("LSL").unlockedBy("has_chiseled_stone_bricks", RootsRecipeProvider.has((ItemLike)Blocks.CHISELED_STONE_BRICKS)).save(consumer);
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)RootsRegistry.MUNDANE_STANDING_STONE.get())).define(Character.valueOf('S'), Tags.Items.STONES).define(Character.valueOf('B'), (ItemLike)Blocks.STONE_BRICKS).define(Character.valueOf('L'), Tags.Items.STORAGE_BLOCKS_LAPIS).pattern("SBS").pattern("BLB").pattern("SBS").unlockedBy("has_lapis_block", RootsRecipeProvider.has((TagKey)Tags.Items.STORAGE_BLOCKS_LAPIS)).save(consumer);
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)RootsRegistry.ATTUNED_STANDING_STONE.get())).define(Character.valueOf('S'), Tags.Items.STONES).define(Character.valueOf('N'), (ItemLike)Items.NETHER_BRICK).define(Character.valueOf('D'), Tags.Items.GEMS_DIAMOND).pattern("SNS").pattern("NDN").pattern("SNS").unlockedBy("has_diamond", RootsRecipeProvider.has((TagKey)Tags.Items.GEMS_DIAMOND)).save(consumer);
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)RootsRegistry.BRAZIER.get())).define(Character.valueOf('I'), Tags.Items.INGOTS_IRON).define(Character.valueOf('S'), Tags.Items.STRINGS).define(Character.valueOf('C'), (ItemLike)Items.CAULDRON).define(Character.valueOf('X'), Tags.Items.RODS_WOODEN).pattern("ISI").pattern("ICI").pattern("IXI").unlockedBy("has_cauldron", RootsRecipeProvider.has((ItemLike)Items.CAULDRON)).save(consumer);
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)RootsRegistry.ALTAR.get())).define(Character.valueOf('S'), Tags.Items.STONES).define(Character.valueOf('F'), (ItemLike)Items.POPPY).define(Character.valueOf('B'), (ItemLike)RootsRegistry.VERDANT_SPRIG.get()).define(Character.valueOf('G'), Tags.Items.STORAGE_BLOCKS_GOLD).define(Character.valueOf('C'), (ItemLike)Blocks.CHISELED_STONE_BRICKS).pattern("BFB").pattern("SGS").pattern(" C ").unlockedBy("has_gold_block", RootsRecipeProvider.has((TagKey)Tags.Items.STORAGE_BLOCKS_GOLD)).save(consumer);
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.TOOLS, (ItemLike)((ItemLike)RootsRegistry.BARK_KNIFE.get())).define(Character.valueOf('S'), Tags.Items.RODS_WOODEN).define(Character.valueOf('V'), ItemTags.SAPLINGS).define(Character.valueOf('P'), ItemTags.PLANKS).pattern(" VV").pattern("VPV").pattern("SV ").unlockedBy("has_sapling", RootsRecipeProvider.has((TagKey)ItemTags.SAPLINGS)).save(consumer);
        ShapedRecipeBuilder.shaped((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)RootsRegistry.RUNIC_TABLET.get())).define(Character.valueOf('S'), Tags.Items.SEEDS_WHEAT).define(Character.valueOf('B'), Tags.Items.STONES).define(Character.valueOf('R'), (ItemLike)RootsRegistry.OLD_ROOT.get()).pattern(" R ").pattern("SBS").pattern(" S ").unlockedBy("has_old_root", RootsRecipeProvider.has((ItemLike)((ItemLike)RootsRegistry.OLD_ROOT.get()))).save(consumer);
        ShapelessRecipeBuilder.shapeless((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)RootsRegistry.GROWTH_POWDER.get()), (int)4).requires(Tags.Items.SEEDS_WHEAT).requires((ItemLike)Items.SHORT_GRASS).requires(Tags.Items.DUSTS_REDSTONE).requires((ItemLike)RootsRegistry.PESTLE.get()).unlockedBy("has_pestle", RootsRecipeProvider.has((ItemLike)((ItemLike)RootsRegistry.PESTLE.get()))).save(consumer);
        ShapelessRecipeBuilder.shapeless((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)RootsRegistry.MUTATING_POWDER.get())).requires((ItemLike)RootsRegistry.GROWTH_POWDER.get()).requires((ItemLike)RootsRegistry.GROWTH_POWDER.get()).requires((ItemLike)RootsRegistry.GROWTH_POWDER.get()).requires((ItemLike)RootsRegistry.GROWTH_POWDER.get()).requires(Tags.Items.NETHER_STARS).requires(Tags.Items.CROPS_NETHER_WART).requires((ItemLike)RootsRegistry.PESTLE.get()).unlockedBy("has_pestle", RootsRecipeProvider.has((ItemLike)((ItemLike)RootsRegistry.PESTLE.get()))).save(consumer);
        ShapelessRecipeBuilder.shapeless((RecipeCategory)RecipeCategory.FOOD, (ItemLike)((ItemLike)RootsRegistry.ROOTY_STEW.get())).requires(Tags.Items.CROPS_WHEAT).requires((ItemLike)Items.BOWL).requires((ItemLike)RootsRegistry.OLD_ROOT.get()).unlockedBy("has_bowl", RootsRecipeProvider.has((ItemLike)Items.BOWL)).save(consumer);
        ShapelessRecipeBuilder.shapeless((RecipeCategory)RecipeCategory.FOOD, (ItemLike)((ItemLike)RootsRegistry.FRUIT_SALAD.get())).requires((ItemLike)Items.MELON).requires((ItemLike)Items.MELON).requires((ItemLike)Items.MELON).requires((ItemLike)Items.APPLE).requires((ItemLike)Items.BOWL).requires((ItemLike)RootsRegistry.ELDERBERRY.get()).requires((ItemLike)RootsRegistry.WHITECURRANT.get()).requires((ItemLike)RootsRegistry.BLACKCURRANT.get()).requires((ItemLike)RootsRegistry.REDCURRANT.get()).unlockedBy("has_bowl", RootsRecipeProvider.has((ItemLike)Items.BOWL)).save(consumer);
        ShapelessRecipeBuilder.shapeless((RecipeCategory)RecipeCategory.MISC, (ItemLike)((ItemLike)RootsRegistry.HEALING_POULTICE.get()), (int)2).requires((ItemLike)RootsRegistry.REDCURRANT.get()).requires((ItemLike)Items.PAPER).requires((ItemLike)RootsRegistry.PESTLE.get()).requires((ItemLike)RootsRegistry.VERDANT_SPRIG.get()).unlockedBy("has_pestle", RootsRecipeProvider.has((ItemLike)((ItemLike)RootsRegistry.PESTLE.get()))).save(consumer);
        SimpleCookingRecipeBuilder.smelting((Ingredient)Ingredient.of((ItemLike[])new ItemLike[]{(ItemLike)RootsRegistry.DRAGONS_EYE.get()}), (RecipeCategory)RecipeCategory.MISC, (ItemLike)Items.ENDER_PEARL, (float)1.0f, (int)200).unlockedBy("has_dragons_eye", RootsRecipeProvider.has((ItemLike)((ItemLike)RootsRegistry.DRAGONS_EYE.get()))).save(consumer, "rootsclassic:ender_pearl");
        new ComponentRecipeBuilder(ComponentRegistry.ALLIUM.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.ALLIUM}), Ingredient.of((ItemLike[])new ItemLike[]{Items.SOUL_SAND}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BROWN_MUSHROOM}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.ELDERBERRY})).save(consumer, Const.modLoc("component/allium"));
        new ComponentRecipeBuilder(ComponentRegistry.APPLE.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.APPLE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GLISTERING_MELON_SLICE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GOLDEN_APPLE}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.BLACKCURRANT})).save(consumer, Const.modLoc("component/apple"));
        new ComponentRecipeBuilder(ComponentRegistry.AZURE_BLUET.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.AZURE_BLUET}), Ingredient.of((ItemLike[])new ItemLike[]{Items.IRON_INGOT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.SPRUCE_SAPLING}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.WHITECURRANT})).save(consumer, Const.modLoc("component/azure_bluet"));
        new ComponentRecipeBuilder(ComponentRegistry.BLUE_ORCHID.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.BLUE_ORCHID}), Ingredient.of((ItemLike[])new ItemLike[]{Items.PRISMARINE_SHARD}), Ingredient.of((ItemLike[])new ItemLike[]{Items.LAPIS_LAZULI}), Ingredient.of((ItemLike[])new ItemLike[]{Items.VINE})).save(consumer, Const.modLoc("component/blue_orchid"));
        new ComponentRecipeBuilder(ComponentRegistry.CHORUS.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.CHORUS_FRUIT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.ENDER_PEARL}), Ingredient.of((ItemLike[])new ItemLike[]{Items.PURPLE_DYE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.POPPED_CHORUS_FRUIT})).save(consumer, Const.modLoc("component/chorus"));
        new ComponentRecipeBuilder(ComponentRegistry.DANDELION.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.DANDELION}), Ingredient.of((ItemLike[])new ItemLike[]{Items.STRING}), Ingredient.of((ItemLike[])new ItemLike[]{Items.FEATHER}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.WHITECURRANT})).save(consumer, Const.modLoc("component/dandelion"));
        new ComponentRecipeBuilder(ComponentRegistry.FLARE_ORCHID.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.NETHERRACK}), Ingredient.of((ItemLike[])new ItemLike[]{Items.MAGMA_CREAM}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BLAZE_ROD}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.FLARE_ORCHID})).save(consumer, Const.modLoc("component/flare_orchid"));
        new ComponentRecipeBuilder(ComponentRegistry.LILAC.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.LILAC}), Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BEETROOT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.VINE})).save(consumer, Const.modLoc("component/lilac"));
        new ComponentRecipeBuilder(ComponentRegistry.LILY_PAD.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.LILY_PAD}), Ingredient.of((ItemLike[])new ItemLike[]{Items.WET_SPONGE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BEETROOT}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.BLACKCURRANT})).save(consumer, Const.modLoc("component/lily_pad"));
        new ComponentRecipeBuilder(ComponentRegistry.MIDNIGHT_BLOOM.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.OBSIDIAN}), Ingredient.of((ItemLike[])new ItemLike[]{Items.DRAGON_BREATH}), Ingredient.of((ItemLike[])new ItemLike[]{Items.DIAMOND}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.MIDNIGHT_BLOOM})).save(consumer, Const.modLoc("component/midnight_bloom"));
        new ComponentRecipeBuilder(ComponentRegistry.NETHER_WART.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.NETHER_WART}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BLAZE_POWDER}), Ingredient.of((ItemLike[])new ItemLike[]{Items.COAL}), Ingredient.of((ItemLike[])new ItemLike[]{Items.CHARCOAL})).save(consumer, Const.modLoc("component/nether_wart"));
        new ComponentRecipeBuilder(ComponentRegistry.ORANGE_TULIP.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.ORANGE_TULIP}), Ingredient.of((ItemLike[])new ItemLike[]{Items.SPONGE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.LEATHER}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.REDCURRANT})).save(consumer, Const.modLoc("component/orange_tulip"));
        new ComponentRecipeBuilder(ComponentRegistry.OXEYE_DAISY.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.OXEYE_DAISY}), Ingredient.of((ItemLike[])new ItemLike[]{Items.END_STONE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GOLD_INGOT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.SUGAR})).save(consumer, Const.modLoc("component/oxeye_daisy"));
        new ComponentRecipeBuilder(ComponentRegistry.PEONY.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.PEONY}), Ingredient.of((ItemLike[])new ItemLike[]{Items.MELON}), Ingredient.of((ItemLike[])new ItemLike[]{Items.RED_DYE}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.NIGHTSHADE})).save(consumer, Const.modLoc("component/peony"));
        new ComponentRecipeBuilder(ComponentRegistry.PINK_TULIP.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.PINK_TULIP}), Ingredient.of((ItemLike[])new ItemLike[]{Items.MELON_SEEDS}), Ingredient.of((ItemLike[])new ItemLike[]{Items.PORKCHOP}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GRANITE})).save(consumer, Const.modLoc("component/pink_tulip"));
        new ComponentRecipeBuilder(ComponentRegistry.POISONOUS_POTATO.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.POISONOUS_POTATO}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GLASS}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GLOWSTONE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.SUGAR_CANE})).save(consumer, Const.modLoc("component/poisonous_potato"));
        new ComponentRecipeBuilder(ComponentRegistry.POPPY.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.POPPY}), Ingredient.of((ItemLike[])new ItemLike[]{Items.RED_MUSHROOM}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BEEF}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.REDCURRANT})).save(consumer, Const.modLoc("component/poppy"));
        new ComponentRecipeBuilder(ComponentRegistry.RADIANT_DAISY.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.REDSTONE_BLOCK}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GLOWSTONE}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.NIGHTSHADE}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.RADIANT_DAISY})).save(consumer, Const.modLoc("component/radiant_daisy"));
        new ComponentRecipeBuilder(ComponentRegistry.RED_TULIP.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.RED_TULIP}), Ingredient.of((ItemLike[])new ItemLike[]{Items.NETHER_BRICK}), Ingredient.of((ItemLike[])new ItemLike[]{Items.QUARTZ}), Ingredient.of((ItemLike[])new ItemLike[]{Items.RED_SAND})).save(consumer, Const.modLoc("component/red_tulip"));
        new ComponentRecipeBuilder(ComponentRegistry.ROSE_BUSH.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.ROSE_BUSH}), Ingredient.of((ItemLike[])new ItemLike[]{Items.FERMENTED_SPIDER_EYE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.IRON_NUGGET}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE})).save(consumer, Const.modLoc("component/rose_bush"));
        new ComponentRecipeBuilder(ComponentRegistry.SUNFLOWER.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.SUNFLOWER}), Ingredient.of((ItemLike[])new ItemLike[]{Items.JACK_O_LANTERN}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE_MEAL}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.ELDERBERRY})).save(consumer, Const.modLoc("component/sunflower"));
        new ComponentRecipeBuilder(ComponentRegistry.WHITE_TULIP.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.WHITE_TULIP}), Ingredient.of((ItemLike[])new ItemLike[]{Items.SNOWBALL}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BIRCH_SAPLING}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.WHITECURRANT})).save(consumer, Const.modLoc("component/white_tulip"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.ACCELERATOR_STANDING_STONE.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.ATTUNED_STANDING_STONE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GLOWSTONE_DUST}), Ingredient.of((ItemLike[])new ItemLike[]{Items.STONE_BRICKS})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.VERDANT_SPRIG}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.INFERNAL_BULB}), Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.JUNGLE_BARK})).level(2).color("#006949").save(consumer, Const.modLoc("ritual/crafting/accelerator_standing_stone"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.AESTHETIC_STANDING_STONE.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.ATTUNED_STANDING_STONE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GLOWSTONE_DUST}), Ingredient.of((ItemLike[])new ItemLike[]{Items.MOSSY_STONE_BRICKS})).level(2).color("#006949").save(consumer, Const.modLoc("ritual/crafting/aesthetic_standing_stone"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.CHARGED_RUNIC_FOCUS.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.RUNIC_FOCUS}), Ingredient.of((ItemLike[])new ItemLike[]{Items.REDSTONE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GLOWSTONE_DUST})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.INFERNAL_BULB}), Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT})).level(0).color("#00f26d").save(consumer, Const.modLoc("ritual/crafting/charged_runic_focus"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.CRYSTAL_STAFF.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.DIAMOND_BLOCK}), Ingredient.of((ItemLike[])new ItemLike[]{Items.STICK}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BLAZE_POWDER})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.COAL_BLOCK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.ACACIA_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.VERDANT_SPRIG}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.BIRCH_BARK})).level(2).color("#cd5600").save(consumer, Const.modLoc("ritual/crafting/crystal_staff"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.GROWER_STANDING_STONE.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.ATTUNED_STANDING_STONE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GLOWSTONE_DUST}), Ingredient.of((ItemLike[])new ItemLike[]{Items.STONE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.VERDANT_SPRIG}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.INFERNAL_BULB}), Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.BIRCH_BARK})).level(2).color("#006949").save(consumer, Const.modLoc("ritual/crafting/grower_standing_stone"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.HEALER_STANDING_STONE.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.ATTUNED_STANDING_STONE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.REDSTONE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.CHISELED_STONE_BRICKS})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.VERDANT_SPRIG}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.INFERNAL_BULB}), Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GHAST_TEAR})).level(2).color("#006949").save(consumer, Const.modLoc("ritual/crafting/healer_standing_stone"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.IGNITER_STANDING_STONE.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.ATTUNED_STANDING_STONE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.REDSTONE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.CRACKED_STONE_BRICKS})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.VERDANT_SPRIG}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.INFERNAL_BULB}), Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.ACACIA_BARK})).level(2).color("#006949").save(consumer, Const.modLoc("ritual/crafting/igniter_standing_stone"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.LIVING_AXE.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.WOODEN_AXE}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.VERDANT_SPRIG}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GOLD_NUGGET})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK})).color("#92d62b").save(consumer, Const.modLoc("ritual/crafting/living_axe"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.LIVING_HOE.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.WOODEN_HOE}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.VERDANT_SPRIG}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GOLD_NUGGET})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK})).color("#92d62b").save(consumer, Const.modLoc("ritual/crafting/living_hoe"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.LIVING_PICKAXE.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.WOODEN_PICKAXE}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.VERDANT_SPRIG}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GOLD_NUGGET})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK})).color("#92d62b").save(consumer, Const.modLoc("ritual/crafting/living_pickaxe"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.LIVING_SHOVEL.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.WOODEN_SHOVEL}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.VERDANT_SPRIG}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GOLD_NUGGET})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK})).color("#92d62b").save(consumer, Const.modLoc("ritual/crafting/living_shovel"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.LIVING_SWORD.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.WOODEN_SWORD}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.VERDANT_SPRIG}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GOLD_NUGGET})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK})).color("#92d62b").save(consumer, Const.modLoc("ritual/crafting/living_sword"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.REPULSOR_STANDING_STONE.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.ATTUNED_STANDING_STONE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GLOWSTONE_DUST}), Ingredient.of((ItemLike[])new ItemLike[]{Items.CHISELED_STONE_BRICKS})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.VERDANT_SPRIG}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.INFERNAL_BULB}), Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.SPRUCE_BARK})).level(2).color("#006949").save(consumer, Const.modLoc("ritual/crafting/repulsor_standing_stone"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.RUNIC_FOCUS.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.VERDANT_SPRIG}), Ingredient.of((ItemLike[])new ItemLike[]{Items.DIAMOND}), Ingredient.of((ItemLike[])new ItemLike[]{Items.STONE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.SPRUCE_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.ACACIA_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.JUNGLE_BARK})).level(2).color("#00f26d").save(consumer, Const.modLoc("ritual/crafting/runic_focus"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.SYLVAN_BOOTS.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.DIAMOND}), Ingredient.of((ItemLike[])new ItemLike[]{Items.LEATHER_BOOTS}), Ingredient.of((ItemLike[])new ItemLike[]{Items.VINE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.BIRCH_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.BIRCH_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GOLDEN_APPLE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.POPPY})).level(2).color("#3e8a3e").save(consumer, Const.modLoc("ritual/crafting/sylvan_boots"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.SYLVAN_HOOD.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.DIAMOND}), Ingredient.of((ItemLike[])new ItemLike[]{Items.LEATHER_HELMET}), Ingredient.of((ItemLike[])new ItemLike[]{Items.VINE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.BIRCH_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.BIRCH_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GOLDEN_APPLE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.POPPY})).level(2).color("#3e8a3e").save(consumer, Const.modLoc("ritual/crafting/sylvan_hood"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.SYLVAN_ROBE.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.DIAMOND}), Ingredient.of((ItemLike[])new ItemLike[]{Items.LEATHER_CHESTPLATE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.VINE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.BIRCH_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.BIRCH_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GOLDEN_APPLE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.POPPY})).level(2).color("#3e8a3e").save(consumer, Const.modLoc("ritual/crafting/sylvan_robe"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.SYLVAN_TUNIC.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.DIAMOND}), Ingredient.of((ItemLike[])new ItemLike[]{Items.LEATHER_LEGGINGS}), Ingredient.of((ItemLike[])new ItemLike[]{Items.VINE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.BIRCH_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.BIRCH_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GOLDEN_APPLE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.POPPY})).level(2).color("#3e8a3e").save(consumer, Const.modLoc("ritual/crafting/sylvan_tunic"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.VACUUM_STANDING_STONE.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.ATTUNED_STANDING_STONE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GLOWSTONE_DUST}), Ingredient.of((ItemLike[])new ItemLike[]{Items.NETHER_BRICKS})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.VERDANT_SPRIG}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.INFERNAL_BULB}), Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.DARK_OAK_BARK})).level(2).color("#006949").save(consumer, Const.modLoc("ritual/crafting/vacuum_standing_stone"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.WILDWOOD_BOOTS.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.DIAMOND}), Ingredient.of((ItemLike[])new ItemLike[]{Items.IRON_BOOTS}), Ingredient.of((ItemLike[])new ItemLike[]{Items.OAK_PLANKS})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.OAK_SAPLING})).level(2).color("#917341").save(consumer, Const.modLoc("ritual/crafting/wildwood_boots"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.WILDWOOD_LEGGINGS.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.DIAMOND}), Ingredient.of((ItemLike[])new ItemLike[]{Items.IRON_LEGGINGS}), Ingredient.of((ItemLike[])new ItemLike[]{Items.OAK_PLANKS})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.OAK_SAPLING})).level(2).color("#917341").save(consumer, Const.modLoc("ritual/crafting/wildwood_leggings"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.WILDWOOD_MASK.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.DIAMOND}), Ingredient.of((ItemLike[])new ItemLike[]{Items.IRON_HELMET}), Ingredient.of((ItemLike[])new ItemLike[]{Items.OAK_PLANKS})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.OAK_SAPLING})).level(2).color("#917341").save(consumer, Const.modLoc("ritual/crafting/wildwood_mask"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.WILDWOOD_PLATE.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.DIAMOND}), Ingredient.of((ItemLike[])new ItemLike[]{Items.IRON_CHESTPLATE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.OAK_PLANKS})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.OAK_SAPLING})).level(2).color("#917341").save(consumer, Const.modLoc("ritual/crafting/wildwood_plate"));
        new RitualRecipeBuilder(RitualRegistry.CRAFTING.getId()).config(this.stackTag(RootsRegistry.ENTANGLER_STANDING_STONE.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.ATTUNED_STANDING_STONE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GLOWSTONE_DUST}), Ingredient.of((ItemLike[])new ItemLike[]{Items.CRACKED_STONE_BRICKS})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.VERDANT_SPRIG}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.INFERNAL_BULB}), Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OAK_BARK})).level(2).color("#006949").save(consumer, Const.modLoc("ritual/crafting/entangler_standing_stone"));
        new RitualRecipeBuilder(RitualRegistry.ENGRAVED_CRAFTING.getId()).config(this.stackTag(RootsRegistry.ENGRAVED_BLADE.toStack(), holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.STONE_SWORD}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.RUNIC_FOCUS}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GLOWSTONE_DUST})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.GOLDEN_CARROT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GOLDEN_APPLE})).level(2).color("#686a6b").save(consumer, Const.modLoc("ritual/crafting/engraved_crafting"));
        new RitualRecipeBuilder(RitualRegistry.SUMMONING.getId()).config(this.entityTag(EntityType.CAVE_SPIDER, holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.STRING}), Ingredient.of((ItemLike[])new ItemLike[]{Items.FERMENTED_SPIDER_EYE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.COAL}), Ingredient.of((ItemLike[])new ItemLike[]{Items.NETHER_WART})).level(2).color("#3a0254").save(consumer, Const.modLoc("ritual/summoning/cave_spider"));
        new RitualRecipeBuilder(RitualRegistry.SUMMONING.getId()).config(this.entityTag(EntityType.CHICKEN, holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.CHICKEN}), Ingredient.of((ItemLike[])new ItemLike[]{Items.FEATHER}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT_SEEDS}), Ingredient.of((ItemLike[])new ItemLike[]{Items.NETHER_WART})).level(1).color("#c769c1").save(consumer, Const.modLoc("ritual/summoning/chicken"));
        new RitualRecipeBuilder(RitualRegistry.SUMMONING.getId()).config(this.entityTag(EntityType.COW, holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.BEEF}), Ingredient.of((ItemLike[])new ItemLike[]{Items.LEATHER}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT_SEEDS}), Ingredient.of((ItemLike[])new ItemLike[]{Items.NETHER_WART})).level(1).color("#c769c1").save(consumer, Const.modLoc("ritual/summoning/cow"));
        new RitualRecipeBuilder(RitualRegistry.SUMMONING.getId()).config(this.entityTag(EntityType.CREEPER, holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.GUNPOWDER}), Ingredient.of((ItemLike[])new ItemLike[]{Items.GUNPOWDER}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.COAL}), Ingredient.of((ItemLike[])new ItemLike[]{Items.NETHER_WART})).level(2).color("#3a0254").save(consumer, Const.modLoc("ritual/summoning/creeper"));
        new RitualRecipeBuilder(RitualRegistry.SUMMONING.getId()).config(this.entityTag(EntityType.ENDERMAN, holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.ENDER_PEARL}), Ingredient.of((ItemLike[])new ItemLike[]{Items.ENDER_PEARL}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.COAL}), Ingredient.of((ItemLike[])new ItemLike[]{Items.NETHER_WART})).level(2).color("#3a0254").save(consumer, Const.modLoc("ritual/summoning/enderman"));
        new RitualRecipeBuilder(RitualRegistry.SUMMONING.getId()).config(this.entityTag(EntityType.PIG, holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.PORKCHOP}), Ingredient.of((ItemLike[])new ItemLike[]{Items.PORKCHOP}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT_SEEDS}), Ingredient.of((ItemLike[])new ItemLike[]{Items.NETHER_WART})).level(1).color("#c769c1").save(consumer, Const.modLoc("ritual/summoning/pig"));
        new RitualRecipeBuilder(RitualRegistry.SUMMONING.getId()).config(this.entityTag(EntityType.RABBIT, holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.RABBIT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.RABBIT_HIDE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT_SEEDS}), Ingredient.of((ItemLike[])new ItemLike[]{Items.NETHER_WART})).level(1).color("#c769c1").save(consumer, Const.modLoc("ritual/summoning/rabbit"));
        new RitualRecipeBuilder(RitualRegistry.SUMMONING.getId()).config(this.entityTag(EntityType.SHEEP, holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.MUTTON}), Ingredient.of((TagKey)ItemTags.WOOL), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT_SEEDS}), Ingredient.of((ItemLike[])new ItemLike[]{Items.NETHER_WART})).level(1).color("#c769c1").save(consumer, Const.modLoc("ritual/summoning/sheep"));
        new RitualRecipeBuilder(RitualRegistry.SUMMONING.getId()).config(this.entityTag(EntityType.SKELETON, holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.ARROW}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.COAL}), Ingredient.of((ItemLike[])new ItemLike[]{Items.NETHER_WART})).level(2).color("#3a0254").save(consumer, Const.modLoc("ritual/summoning/skeleton"));
        new RitualRecipeBuilder(RitualRegistry.SUMMONING.getId()).config(this.entityTag(EntityType.SLIME, holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.SLIME_BALL}), Ingredient.of((ItemLike[])new ItemLike[]{Items.SLIME_BALL}), Ingredient.of((ItemLike[])new ItemLike[]{Items.SLIME_BALL})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.COAL}), Ingredient.of((ItemLike[])new ItemLike[]{Items.NETHER_WART})).level(2).color("#3a0254").save(consumer, Const.modLoc("ritual/summoning/slime"));
        new RitualRecipeBuilder(RitualRegistry.SUMMONING.getId()).config(this.entityTag(EntityType.SPIDER, holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.STRING}), Ingredient.of((ItemLike[])new ItemLike[]{Items.SPIDER_EYE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.COAL}), Ingredient.of((ItemLike[])new ItemLike[]{Items.NETHER_WART})).level(2).color("#3a0254").save(consumer, Const.modLoc("ritual/summoning/spider"));
        new RitualRecipeBuilder(RitualRegistry.SUMMONING.getId()).config(this.entityTag(EntityType.ZOMBIE, holderLookup)).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.ROTTEN_FLESH}), Ingredient.of((ItemLike[])new ItemLike[]{Items.ROTTEN_FLESH}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.COAL}), Ingredient.of((ItemLike[])new ItemLike[]{Items.NETHER_WART})).level(2).color("#3a0254").save(consumer, Const.modLoc("ritual/summoning/zombie"));
        new RitualRecipeBuilder(RitualRegistry.BANISH_RAIN.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.VINE}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.OLD_ROOT})).level(1).color("#cc9f23").save(consumer, Const.modLoc("ritual/banish_rain"));
        new RitualRecipeBuilder(RitualRegistry.CAUSE_RAIN.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.LILY_PAD})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.VINE})).level(1).color("#17008a").save(consumer, Const.modLoc("ritual/cause_rain"));
        new RitualRecipeBuilder(RitualRegistry.FLARE.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.FLINT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.COAL}), Ingredient.of((ItemLike[])new ItemLike[]{Items.CHARCOAL})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.GUNPOWDER}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.INFERNAL_BULB})).level(1).color("#ff5b19").save(consumer, Const.modLoc("ritual/flare"));
        new RitualRecipeBuilder(RitualRegistry.GROW.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.REDSTONE}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE_MEAL}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.VERDANT_SPRIG})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BEETROOT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.POTATO}), Ingredient.of((ItemLike[])new ItemLike[]{Items.CARROT})).color("#52d42f").save(consumer, Const.modLoc("ritual/grow"));
        new RitualRecipeBuilder(RitualRegistry.IMBUER.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.CRYSTAL_STAFF}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.VERDANT_SPRIG})).level(1).color("#ffffff").save(consumer, Const.modLoc("ritual/imbuer"));
        new RitualRecipeBuilder(RitualRegistry.LIFE_DRAIN.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.BLAZE_POWDER}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.WOODEN_SWORD}), Ingredient.of((ItemLike[])new ItemLike[]{Items.WOODEN_AXE}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.DARK_OAK_BARK}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.BIRCH_BARK})).color("#8b1628").save(consumer, Const.modLoc("ritual/life_drain"));
        new RitualRecipeBuilder(RitualRegistry.MASS_BREEDING.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.GLOWSTONE_DUST}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.CARROT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.WHEAT_SEEDS}), Ingredient.of((ItemLike[])new ItemLike[]{Items.COD})).level(2).color("#943d51").save(consumer, Const.modLoc("ritual/mass_breeding"));
        new RitualRecipeBuilder(RitualRegistry.SACRIFICE.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.FLINT}), Ingredient.of((ItemLike[])new ItemLike[]{Items.IRON_SWORD}), Ingredient.of((ItemLike[])new ItemLike[]{Items.BONE})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.BLAZE_POWDER}), Ingredient.of((ItemLike[])new ItemLike[]{RootsRegistry.DARK_OAK_BARK})).level(2).color("#5e0938").save(consumer, Const.modLoc("ritual/sacrifice"));
        new RitualRecipeBuilder(RitualRegistry.TIME_SHIFT.getId()).materials(Ingredient.of((ItemLike[])new ItemLike[]{Items.CLOCK}), Ingredient.of((ItemLike[])new ItemLike[]{Items.IRON_INGOT})).incenses(Ingredient.of((ItemLike[])new ItemLike[]{Items.CLOCK})).level(1).color("#f0f563").secondaryColor("#fca223").save(consumer, Const.modLoc("ritual/time_shift"));
    }

    private CompoundTag stackTag(ItemStack stack, HolderLookup.Provider holderLookup) {
        CompoundTag tag = new CompoundTag();
        tag.put("result", stack.save(holderLookup, (Tag)new CompoundTag()));
        return tag;
    }

    private CompoundTag entityTag(EntityType<?> entityType, HolderLookup.Provider holderLookup) {
        CompoundTag tag = new CompoundTag();
        tag.putString("entity", BuiltInRegistries.ENTITY_TYPE.getKey(entityType).toString());
        return tag;
    }
}

